
openapi: 3.0.0
info:
  title: RAPIDOS API
  version: 1.0.0
  description: API de mise en réseau des utiliseurs(acheteur,vendeur,livreurs) utilisateur avec envoi OTP (email ou WhatsApp)
servers:
  - url: http://localhost:3333

paths:
  /register:
    post:
      summary: Inscription utilisateur avec envoi OTP
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
                - email
                - password
                - firstName
                - lastName
                - phone
                - termsAccepted
              properties:
                role:
                  type: string
                  enum: [acheteur, vendeur, livreur, admin, superadmin]
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 12
                  maxLength: 64
                  description: Mot de passe avec majuscule, minuscule, chiffre, caractère spécial
                firstName:
                  type: string
                lastName:
                  type: string
                phone:
                  type: string
                  pattern: "^\+[1-9]\d{1,14}$"
                  example: "+243818379907"
                termsAccepted:
                  type: boolean
                  example: true
      responses:
        '201':
          description: Inscription réussie, OTP envoyé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: saisir le opt pour continuer
                  status:
                    type: integer
                    example: 201
                  id:
                    type: string
        '400':
          description: Données invalides
        '409':
          description: L'utilisateur existe déjà
        '500':
          description: Erreur serveur interne

  /verify-otp/{userId}:
    post:
      summary: Vérification du code OTP
      tags:
        - Auth
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: OTP vérifié avec succès, token retourné
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: bearer
                  value:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  expiresIn:
                    type: string
                    format: date-time
                  userId:
                    type: string
        '400':
          description: OTP invalide ou expiré
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur serveur interne