openapi: 3.0.0
info:
  title: RAPIDOS API
  version: 1.0.0
  description: API de mise en réseau des utilisateurs (acheteur, vendeur, livreur) avec envoi OTP (email ou WhatsApp)

servers:
  - url: http://localhost:3333

paths:
  /:
    get:
      summary: Vérifie que l’API fonctionne
      responses:
        '200':
          description: API opérationnelle

  /register:
    post:
      summary: Enregistrement d’un utilisateur
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - firstName
                - lastName
                - phone
                - role
                - termsAccepted
              properties:
                email:
                  type: string
                  example: utilisateur@example.com
                password:
                  type: string
                  example: MonmotDePasse123!
                firstName:
                  type: string
                  example: Judah
                lastName:
                  type: string
                  example: Mvi
                phone:
                  type: string
                  example: '+2250700000000'
                role:
                  type: string
                  example: vendeur
                termsAccepted:
                  type: boolean
                  example: true
      responses:
        '201':
          description: Utilisateur enregistré avec succès
        '400':
          description: Données invalides
        '500':
          description: Erreur interne

  /verify-otp/{userId}:
    post:
      summary: Vérifie le code OTP d’un utilisateur
      tags:
        - Authentification
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Authentification réussie
        '400':
          description: Code OTP invalide
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur interne

  /login:
    post:
      summary: Authentification d’un utilisateur (email ou téléphone)
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - uid
                - password
              properties:
                uid:
                  type: string
                  description: Email ou numéro de téléphone
                  example: +243819493091
                password:
                  type: string
                  example: MonMotDePasse123!
      responses:
        '200':
          description: Connexion réussie avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Connexion réussie avec succès
                  token:
                    type: object
                    properties:
                      type:
                        type: string
                        example: bearer
                      name:
                        type: string
                        nullable: true
                        example: null
                      token:
                        type: string
                        example: oat_MTc.LVZjbTZvSXhLWlYwOGJES0F6c01SUWhBWktIVmdkZEY5T3lOZnIxQjgyNTA1NDA2
                      abilities:
                        type: array
                        items:
                          type: string
                        example: ['*']
                      lastUsedAt:
                        type: string
                        nullable: true
                        format: date-time
                        example: null
                      expiresAt:
                        type: string
                        format: date-time
                        example: 2025-06-27T14:26:53.513Z
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 18
                      firstName:
                        type: string
                        example: jojo
                      lastName:
                        type: string
                        example: jojo
                      email:
                        type: string
                        example: jojo@gmail.com
                      phone:
                        type: string
                        example: '+243819493091'
                      role:
                        type: string
                        example: vendeur
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-05-27T16:59:58.495Z
                      updatedAt:
                        type: string
                        format: date-time
                        example: 2025-05-27T16:59:58.525Z
                      secureOtp:
                        type: string
                        example: '238392'
                      otpExpiredAt:
                        type: string
                        format: date-time
                        example: 2025-05-27T17:49:58.522Z
                      termsAccepted:
                        type: boolean
                        example: true
                  status:
                    type: integer
                    example: 200
        '401':
          description: Identifiants invalides ou mot de passe incorrect
        '500':
          description: Erreur interne

  /logout:
    get:
      summary: Déconnexion d’un utilisateur
      tags:
        - Authentification
      responses:
        '200':
          description: Déconnexion réussie
        '401':
          description: Non autorisé

  /users/editable-fields/{userId}:
    get:
      tags:
        - Users
      summary: Récupérer les champs modifiables pour la mise à jour
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Champs récupérés avec succès
        '401':
          description: Non autorisé
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur interne

  /users/update/{userId}:
    post:
      tags:
        - Users
      summary: Mettre à jour un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - phone
                - password
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                email:
                  type: string
                role:
                  type: string
                termsAccepted:
                  type: boolean
      responses:
        '200':
          description: Utilisateur mis à jour avec succès
        '400':
          description: Données invalides
        '403':
          description: Non autorisé à modifier cet utilisateur
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur interne

  /users/me:
    get:
      tags:
        - Users
      summary: Récupérer l'utilisateur connecté
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Utilisateur récupéré avec succès
        '500':
          description: Erreur interne

  /users:
    get:
      tags:
        - Users
      summary: Récupérer tous les utilisateurs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Utilisateurs récupérés avec succès
        '403':
          description: Accès refusé
        '500':
          description: Erreur interne

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Récupérer un utilisateur par ID
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilisateur récupéré avec succès
        '403':
          description: Accès interdit
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur interne

    delete:
      tags:
        - Users
      summary: Supprimer un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilisateur supprimé avec succès
        '403':
          description: Vous ne pouvez pas supprimer votre propre compte
        '404':
          description: Utilisateur introuvable
        '500':
          description: Erreur interne

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        role:
          type: string
        termsAccepted:
          type: boolean
